from typing import Protocol

import pygame


class View(Protocol):
    def draw(self, surface: pygame.Surface) -> None: ...
    def handle_event(self, event: pygame.event.Event) -> None: ...
    def activate(self) -> None: ...
    def deactivate(self) -> None: ...
